print('Vou pedir-lhe dois numeros')
x = int(input('Escreva o primeiro numero, x = '))
y = int(input('Escreva o segundo numero, y = '))
conta = (x+3*y)*(x-y)
print('O valor de (x + 3 * y) * (x - y) e:', conta)
